sandbox/urls.py
"""config URL Configuration 4.1"""

from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from src.accounts.views import CustomSignUp
from src.core.utils.views_help import clear, terms
from src.core.views import home

# handler404 = "src.core.utils.views_help.handler404"
# handler500 = "src.core.utils.views_help.handler500"


urlpatterns = [
    # path(eve('SECRET_ADMIN_URL') + '/admin/', admin.site.urls),
    path(
        "i18n/",
        include("django.conf.urls.i18n"),
    ),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path("admin/", admin.site.urls),
    path("contacts/", include("src.contacts.urls")),
    path("notifications/", include("src.notifications.urls")),
    path("in-development/", include("src.devs.urls")),
    path("terms", terms, name="terms"),
]

htmx_urlpatterns = [
    path("clear", clear, name="clear"),
]

urlpatterns += i18n_patterns(
    path("", home, name="home"),
    path("accounts/signup/", CustomSignUp.as_view()),
    path("accounts/", include("allauth.urls")),
    path("core/", include("src.core.urls")),
    path("profile/", include("src.profiles.urls")),
    path("posts/", include("src.posts.urls")),
    path("comments/", include("src.comments.urls")),
)
urlpatterns += htmx_urlpatterns
if "rosetta" in settings.INSTALLED_APPS:
    urlpatterns += [path("rosetta/", include("rosetta.urls"))]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

src/comments/urls.py
from django.urls import path

from .views import (
    DeleteCommentView,
    GetReplyFormView,
    ProccessReplyView,
    display_all_comments,
    display_selected_comments,
    handle_edit_comment,
)

app_name = "comments"

urlpatterns = [
    path("all-comms/<post_uuid>/", display_all_comments, name="all_comms"),
    path(
        "selected-thread/<post_uuid>/<thread_uuid>/",
        display_selected_comments,
        name="select_comms",
    ),
    # create
    path(
        "add-comm/<post_uuid>/<comm_id>/", GetReplyFormView.as_view(), name="add_comm"
    ),
    path(
        "process-reply/<post_uuid>/", ProccessReplyView.as_view(), name="process_comm"
    ),
    # delete
    path(
        "process-delete/<post_uuid>/<comm_id>/",
        DeleteCommentView.as_view(),
        name="handle_delete",
    ),
    # edit
    path("edit-comm/<post_uuid>/<comm_id>/", handle_edit_comment, name="handle_edit"),
]

src/core/urls.py
from django.urls import path

from .views import about, intro, thanks

app_name = "core"

urlpatterns = [
    path("general-info/", intro, name="intro"),
    path("acknowledgments/", thanks, name="thanks"),
    path("about/", about, name="about"),
]

src/devs/urls.py
from django.urls import path

from .views import (
    ChangeState,
    DevDetailPost,
    DevPage,
    MakeNewPost,
    ShowDevPostList,
    SoftDeletePost,
)

app_name = "devs"

urlpatterns = [
    path("", DevPage.as_view(), name="dev_page"),
    path("drafts/<action>/", ShowDevPostList.as_view(), name="selection"),
    path(
        "dev-post-detail/<str:uuid>/",
        DevDetailPost.as_view(),
        name="dev_detail_post",
    ),
    path("soft-delete/<str:uuid>/", SoftDeletePost.as_view(), name="soft_delete_post"),
    path("change-state/<action>/", ChangeState.as_view(), name="change_state"),
    path("creation/", MakeNewPost.as_view(), name="creation"),
]

src/posts/urls.py
from django.urls import path, re_path

from src.posts.views.post_views import (
    PostBookMarkCollection,
    PostCategSearch,
    PostComment,
    PostDatumFilter,
    PostList,
    PostTagSearch,
    SearchPost,
)
from src.posts.views.user_action_views import TrackBookmark, TrackLike

app_name = "posts"

urlpatterns = [
    path("", PostList.as_view(), name="post_list"),
    path("detail/<slug:slug>/", PostComment.as_view(), name="post_detail"),
    path("categ/<slug:slug>/", PostCategSearch.as_view(), name="cat_search"),
    path("search/", SearchPost.as_view(), name="search_posts"),
    re_path(
        r"^tag-search/(?:t:(?P<tag>[-\w]+)/)?$",
        PostTagSearch.as_view(),
        name="tag_search",
    ),
    path(
        "comments/<slug:slug>/<thread_uuid>/", PostComment.as_view(), name="get_branch"
    ),
    path(
        "datum-filter/<year>/<month>/",
        PostDatumFilter.as_view(),
        name="filter_calend",
    ),
    path(
        "change-bookmark/<action>/",
        TrackBookmark.as_view(),
        name="change_bookmark",
    ),
    # part delete bmark => htmx
    path(
        "bmark-collection/", PostBookMarkCollection.as_view(), name="bmark_collection"
    ),
]

htmx_urlpatterns = [
    path("set-like/", TrackLike.as_view(), name="track_likes"),
]
urlpatterns += htmx_urlpatterns

src/accounts/forms.py
from allauth.account.forms import SignupForm
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm as UCF
from django.utils.html import format_html
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserCreationForm(UCF):
    """form to create a new user via admin (door admin)"""

    email = forms.EmailField(
        label=_("Email"),
        max_length=120,
        widget=forms.EmailInput(attrs={"autocomplete": "email"}),
    )

    class Meta(UCF.Meta):
        model = User
        fields = ("username", "email")


# custom allauth form
class CustomSignupForm(SignupForm):
    """add extra field for 'Agree'"""

    username_help_text = "Username should contain at least 3 characters"
    password_help_text = (
        "Password should contain at least 8 characters; can not be entirely numeric"
    )

    def __init__(self, *args, **kwargs):
        """included field "agree to term" needs other css styling"""
        super().__init__(*args, **kwargs)
        self.fields["username"].help_text = self.username_help_text
        self.fields["password1"].help_text = self.password_help_text

        self.fields["agree_to_terms"].widget.attrs = {"type": "checkbox"}
        for field_name, field in self.fields.items():
            if field_name != "agree_to_terms":
                field.widget.attrs = {"class": "form-control border border-4"}
            else:
                field.widget.attrs = {"class": "mt-2 mb-4"}

    agree_to_terms = forms.BooleanField(
        label=format_html(
            _(
                "I agree to the <a class='general' \
                href='/terms'>terms and conditions</a>"
            )
        )
    )

    field_order = ("username", "email", "password1", "password2", "agree_to_terms")

src/accounts/views.py
from allauth.account.views import SignupView
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404, render

User = get_user_model()


class CustomSignUp(SignupView):
    """if user deleted his account=> show account not active template"""

    def form_valid(self, form):
        user_email = form.cleaned_data["email"]
        user_obj = get_object_or_404(User, email=user_email)
        if user_obj is not None and not user_obj.is_active:
            return render(self.request, template_name="account/account_inactive.html")
        print("inside line 14")
        return super().form_valid(form)

src/comments/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin as LRM
from django.http import HttpResponse, HttpResponseForbidden, QueryDict
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.views import View

from src.comments.forms import CommentForm
from src.comments.mixins import CheckRequestMixin
from src.comments.models import Comment
from src.posts.models.post_model import Post

logger = logging.getLogger("user_issues")


def display_all_comments(request, post_uuid):
    """
    htmx based; triggered if post detail page
    loaded or comments updated
    """
    post = Post.objects.get(uuid=post_uuid)
    post_comms = Comment.objects.filter(post=post)
    return render(
        request,
        "components/comms/wraps.html",
        {"comments": post_comms, "post": post, "user": request.user},
    )


def display_selected_comments(request, post_uuid, thread_uuid):
    """
    htmx based;
    triggered from dropdown-menu link:
    comments refer to replied comment and it's children
    """
    post = Post.objects.get(uuid=post_uuid)
    post_comms = Comment.objects.filter(post=post, uuid=thread_uuid)
    return render(
        request,
        "components/comms/wraps.html",
        {"comments": post_comms, "post": post, "user": request.user},
    )


class GetReplyFormView(LRM, CheckRequestMixin, View):
    def get(self, request, post_uuid, comm_id):
        """htmx + modal; get req to get form for reply"""
        form = CommentForm(initial={"comm_parent_id": comm_id})
        ctx = {}
        ctx["form"] = form
        ctx["post_uuid"] = post_uuid
        return render(request, "components/comms/comm_form.html", ctx)


class ProccessReplyView(LRM, CheckRequestMixin, View):
    def post(self, request, post_uuid):
        """
        htmx-modal;
        no notifications in cases:
        - parent(replied) comm is deleted;
        - users comment their own comment
        - banned users filter via template
        """
        form = CommentForm(request.POST)
        if form.is_valid():
            comm_parent_id = form.cleaned_data["comm_parent_id"]
            post = get_object_or_404(Post, uuid=post_uuid)
            parent_comm = get_object_or_404(Comment, id=comm_parent_id)
            replied_to = parent_comm.user
            comm = form.save(commit=False)
            comm_body = form.cleaned_data["body"]
            comm.user = request.user
            comm.reply_to = replied_to
            comm.post = post
            comm.body = comm_body
            if replied_to == request.user:
                comm.own_reply = True
            parent_comm.add_child(instance=comm)
            return HttpResponse(status=204, headers={"HX-Trigger": "updateCommList"})


@login_required
def handle_edit_comment(request, post_uuid, comm_id):
    """
    htmx based + modal UI in bootstrap5;
    provide pre-filled comment form and proccess it.
    incl method PUT (htmx)
    """
    if request.user.banned:
        logger.warning(f"banned user {request.user.id} attempted to edit comment")
        return HttpResponseForbidden()

    ctx = {"post_uuid": post_uuid, "comm_id": comm_id}
    post = get_object_or_404(Post, uuid=post_uuid)
    obj = get_object_or_404(Comment, post_id=post.id, id=comm_id)
    parent = obj.get_parent()
    if request.method == "GET":
        if parent:
            form = CommentForm(instance=obj, initial={"comm_parent_id": comm_id})
        else:
            form = CommentForm(instance=obj)
        ctx["form"] = form
        return render(request, "components/comms/comm_edit_form.html", ctx)

    if request.method == "PUT":
        data_dict = QueryDict(request.body).dict()
        form = CommentForm(data_dict, instance=obj)
        if form.is_valid():
            obj.updated_at = timezone.now()
            obj.save()
            return HttpResponse(status=204, headers={"HX-Trigger": "updateCommList"})
        else:
            ctx["form"] = form
    return render(request, "components/comms/comm_edit_form.html", ctx)


class DeleteCommentView(LRM, CheckRequestMixin, View):
    def get(self, request, post_uuid, comm_id):
        ctx = {"post_uuid": post_uuid, "comm_id": comm_id}
        return render(request, "components/comms/del_confirm.html", ctx)

    def post(self, request, post_uuid, comm_id):
        post = get_object_or_404(Post, uuid=post_uuid)
        comm_to_del = get_object_or_404(Comment, id=comm_id, post_id=post.id)
        comm_to_del.deleted = True
        comm_to_del.save()
        return HttpResponse(status=204, headers={"HX-Trigger": "updateCommList"})

src/contacts/views.py
import logging

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin as LRM
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import View
from django.views.generic.edit import FormView

from src.core.utils.views_help import get_ip
from src.profiles.models import Profile

from .exceptions import HtmxFailureError
from .forms import ContactForm

logger = logging.getLogger("user_issues")


class Subscribe(LRM, View):
    def get(self, request):
        """
        only auth-ed users can subscribe to a news letter
        via menu dropdown item
        """
        return render(
            request,
            "contacts/subscription/confirmation.html",
        )

    def post(self, request, **kwargs):
        """
        htmx_based request with redirect to home page
        and flash msg as a feedback
        """

        htmx_req = request.headers.get("hx-request")

        if request.user.is_authenticated and htmx_req is not None:
            _id = request.user.profile.id
            profile = get_object_or_404(Profile, id=_id)
            profile.want_news = True
            profile.save()
            logger.info(f"{profile.id} succeeded to subscribe for news letter")
            messages.success(request, _("You have subscribed to the news letter"))
            return HttpResponse(
                headers={"HX-Redirect": "/"},
            )
        elif htmx_req is None:
            logger.error(f"{request.user.id} failed htmx to subscribe for news letter")
            raise HtmxFailureError(_("Subscription failed"))


class UnSubscribe(View):
    def get(self, request, **kwargs):
        """
        get request via link in a newsletter
        contains profile uuid
        """
        uuid = kwargs.get("uuid")
        profile = get_object_or_404(Profile, uuid=uuid)
        ctx = {"uuid": profile.uuid}
        return render(request, "contacts/subscription/unsubscribe.html", ctx)

    def post(self, request, **kwargs):
        # htmx_based
        """
        if OK -> redirect ot Home page with success msg
        """
        htmx_req = request.headers.get("hx-request")
        try:
            uuid = kwargs.get("uuid")
            profile = get_object_or_404(Profile, uuid=uuid)
            if htmx_req and profile.want_news:
                profile.want_news = False
                profile.save()
                logger.info(f"{profile.id} succeeded to UNsubscribe for news letter")
                messages.success(request, _("You have unsubscribed to the news letter"))
                return HttpResponse(
                    headers={
                        "HX-Redirect": "/",
                    },
                )
            elif htmx_req is None:
                logger.error(f"{profile.id} failed htmx to Unsubscribe for news letter")
                raise HtmxFailureError(_("Something went wrong.Can't unsubscribe."))
        except HtmxFailureError:
            raise

        return HttpResponseRedirect("/")


class ContactView(FormView):
    """unauth or auth user can send a feedback to admin"""

    template_name = "contacts/feedback/feedback.html"
    form_class = ContactForm
    success_url = reverse_lazy("home")

    def get_form_kwargs(self) -> dict:
        kwargs = super().get_form_kwargs()
        if self.request.user.is_authenticated:
            kwargs.update(
                {
                    "initial": {
                        "name": self.request.user.username,
                        "email": self.request.user.email,
                    }
                }
            )
        return kwargs

    def form_valid(self, form):
        name = form.cleaned_data.get("name")
        email = form.cleaned_data.get("email")
        subject = form.cleaned_data.get("subject")
        message = form.cleaned_data.get("message")
        context = {
            "user": name,
            "subject": subject,
            "email": email,
            "message": message,
        }

        from_email = email
        to_email = ("some-mail@mail.com",)
        contact_message = get_template("contacts/feedback/contact_msg.txt").render(
            context
        )

        # self.send_mail_to_admin() ?
        send_mail(subject, contact_message, from_email, to_email, fail_silently=True)
        remote_address = get_ip(self.request)
        logger.info(f"contact letter sent OK from ip: {remote_address}")

        messages.add_message(
            self.request,
            messages.SUCCESS,
            _("Your message is sent"),
        )

        return HttpResponseRedirect(redirect_to=self.success_url)

src/core/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

from src.posts.models.media_model import Video


def home(request: HttpRequest) -> HttpResponse:
    # ctx = {"vidos": Video.objects.last()}
    return render(request, "core/home.html")  # , ctx)


def intro(request: HttpRequest) -> HttpResponse:
    ctx = {}
    return render(request, "core/intro.html", ctx)


def about(request: HttpRequest) -> HttpResponse:
    ctx = {}
    return render(request, "core/about.html", ctx)


def thanks(request: HttpRequest) -> HttpResponse:
    ctx = {}
    return render(request, "core/acknowledgments.html", ctx)

src/templates/posts/post_bmarks.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <div class="col-md-12 col-sm-12 d-flex flex-wrap" id="post_list">
    {% if posts %}
      {% for post in posts%}
        {% include "posts/parts/post_card.html" %}
      {% endfor %}
   </div>
      {% include "posts/parts/pagination.html" %}
   {% else %}
   <div class="col-md-12 col-sm-12 text-center ">
    <h5>No posts in bookmarks</h5>
   </div>

   {% endif %}
</div>

{% endblock%}

src/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static sidebars i18n tree_comms calend %}
{% block content %}

  <div class="row">
  <aside class="col-md-3 col-sm-12">
    {% show_categs %}

  </aside>
  <div class="col-md-6 col-sm-12" id="post_list">

    <h3>{{post.title}}</h3>
    <p>{{post.published_at|date:"F d, Y"}}</p>

    <div class="d-flex">
      <div class="me-3">
        <strong>{%trans "category" %}</strong>:
      </div>
      {% include "components/post_categs.html" with categ_dict=cats_path %}
    </div>
    {% if post.top_img %}
    <img src="{{post.top_img.url}}" class="img-fluid" alt="post_img">
    {% endif %}
    <div class="content">
        {{post.content|safe}}
    </div>
    <hr>
    <div class="d-flex justify-content-between">
      <div class="d-flex align-self-center">
        <div class="me-5 ms-5">
          {% if user.is_authenticated %}
          <button hx-post="{% url 'posts:track_likes' %}"  hx-target="#likeSpan"
            hx-vals='{
              "post_uuid":"{{post.uuid}}",
              "user_id":"{{user.id}}"
            }' id="toLike" class="btn btn-danger">
            <span id="likeSpan">
              {% if liked %}
                Remove like
              {% else %}
                Click to like
              {% endif %}
              {% if post.count_likes %}
              <span class="circle_num">
              {{post.count_likes}}
            </span>
            {% endif %}
            </span>
          </button>
        {% endif %}
        </div>
      </div>
    {% if user.is_authenticated and display_bmark_button %}
    <div class="me-5 d-flex" id="bmarkDiv">
      <form action="{% url 'posts:change_bookmark' action='add' %}" method="POST" id="bookmark">
        {% csrf_token %}
        <input type="hidden" name="post_uuid" value="{{post.uuid}}">
        <input type="hidden" name = "user_id"  value="{{user.id}}">
        <button class="btn btn-success" type="submit" id="toBookMark">
          <svg viewBox="0 0 16 16" width="1em" height="1em" focusable="false" role="img" aria-label="bookmark heart fill" xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi-bookmark-heart-fill b-icon bi"><g><path d="M2 15.5a.5.5 0 0 0 .74.439L8 13.069l5.26 2.87A.5.5 0 0 0 14 15.5V2a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v13.5zM8 4.41c1.387-1.425 4.854 1.07 0 4.277C3.146 5.48 6.613 2.986 8 4.412z"></path></g></svg><span class="px-2">Add to bookmarks</span></button>
      </form>

    </div>
    {% endif %}
   </div>
   <hr>
   <!-- coments section -->
   <div class="container mt-4">
    <div id="jsBox"></div>
    {% if user.is_authenticated and not user.banned and post.allow_comments %}
      <div class="row">
        <div class="col-md-12 text-center">

          <button class="btn btn-success" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            {% trans "Show form" %}
          </button>
        </div>
      </div>
      <div class="row collapse" id="collapseExample" >
        <div class="col-md-12">

          <form action="{% url 'posts:post_detail' post.slug %}" id="top_form" method="POST" class="form-main"
          >
            {% csrf_token %}
            {% for field in form.visible_fields %}
              <p>{{ field.errors }}</p>
                {{ field }}
              <p class="text-center"><strong>{{ field.help_text }}</strong></p>
            {% endfor %}
            {% for error in field.errors %}
            <div class="errorlist">{{ error }}</div>
            {% endfor %}

            <button class="btn btn-primary" type="submit">Comment</button>
          </form>

        </div>
      </div>
      {% endif %}

      {% if comments %}
      <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-md-12 col-sm-6 number">{% trans 'Comments' %} : {{comms_total}}</div>
        <div class="col-sm-3"></div>

      </div>

      <div class="row comms">
        <div class="col-sm-3"></div>
          <div class="col-sm-6 col-md-12 ">
            {% if thread_uuid %}
            <div class="mb-2"><button class="btn btn-secondary"
            hx-get="{% url 'comments:all_comms' post.uuid %}"
            hx-target="#mycomms"
              >{% trans 'Refresh all comments' %}</button>
            </div>
            <div id="comms_list"
              hx-trigger="load, updateCommList from:body"
              hx-get="{% url 'comments:select_comms' post_uuid=post.uuid thread_uuid=thread_uuid %}"
              hx-target="#mycomms">
              <div id="mycomms"class="comms_bg"></div>
            </div>
            {% else %}
            <div id="comms_list"
            hx-trigger="load, updateCommList from:body"
            hx-get="{% url 'comments:all_comms' post.uuid %}"
            hx-target="#mycomms">
            <div id="mycomms"class="comms_bg"></div>
          </div>

            {% endif %}
          </div>
        <div class="col-sm-3"></div>
      </div>
      {% else %}
      <div class="row">
        <div class="col col-md-12 text-center mt-1">{% trans 'No comments yet. Please, be first to comment' %}</div>
      </div>
      {% endif %}
  </div>
  </div>

  <div class="col-md-3 col-sm-12 d-flex flex-column hidden-mobile">
    {% show_archive %}
    {% show_tags %}
  </div>
  </div>
  <hr>

  <button  id="toTop" title="Go to top" style="display: block;">{% trans "Go Top" %}</button>
{% endblock%}

src/templates/posts/post_list.html
{% extends 'base.html' %}
{% load static sidebars calend i18n %}
{% block content %}
<div class="row d-flex justify-content-center dmb-lg-4 mb-sm-1 pe-sm-0">
  <div class="col col-md-8 mb-2 ">
    <div class="d-flex justify-content-center">
      {% include "components/crumbs.html" %}
    </div>
  </div>
</div>
<div class="wrap">
  <aside class="grid-categs">
        {% show_categs %}
  </aside>
  <div class="grid-content mt-2" id="post_list">
    {% if posts %}
      {% for post in posts%}
        {% include "posts/parts/single_post.html" %}
      {% endfor %}
      {% include "posts/parts/pagination.html" %}
    {% else %}
    <div id="not-found" class="not-found p-2 mt-2">
        {% trans "Sorry. Nothing found for your search" %}
    </div>
    {% include "posts/parts/search_errors.html" %}
    {% endif %}
  </div>
  <div class="grid-archive ">
    {% show_archive %}
  </div>
  <div class="grid-tags">
    {% show_tags %}
  </div>
</div>
<button id="toTop" title="Go to top" style="display: block;">{% trans "Go Top" %}</button>

{% endblock%}
{% block js %}

{% endblock %}