sandbox/urls.py
"""config URL Configuration 4.1"""

from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from src.accounts.views import CustomSignUp
from src.core.utils.views_help import clear, terms
from src.core.views import home

# handler404 = "src.core.utils.views_help.handler404"
# handler500 = "src.core.utils.views_help.handler500"


urlpatterns = [
    # path(eve('SECRET_ADMIN_URL') + '/admin/', admin.site.urls),
    path(
        "i18n/",
        include("django.conf.urls.i18n"),
    ),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path("admin/", admin.site.urls),
    path("contacts/", include("src.contacts.urls")),
    path("notifications/", include("src.notifications.urls")),
    path("in-development/", include("src.devs.urls")),
    path("terms", terms, name="terms"),
]

htmx_urlpatterns = [
    path("clear", clear, name="clear"),
]

urlpatterns += i18n_patterns(
    path("", home, name="home"),
    path("accounts/signup/", CustomSignUp.as_view()),
    path("accounts/", include("allauth.urls")),
    path("core/", include("src.core.urls")),
    path("profile/", include("src.profiles.urls")),
    path("posts/", include("src.posts.urls")),
    path("comments/", include("src.comments.urls")),
)
urlpatterns += htmx_urlpatterns
if "rosetta" in settings.INSTALLED_APPS:
    urlpatterns += [path("rosetta/", include("rosetta.urls"))]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

src/contacts/urls.py
from django.urls import path

from .views import ContactView, Subscribe, UnSubscribe

app_name = "contacts"

urlpatterns = [
    path("subscribe/", Subscribe.as_view(), name="subscribe"),
    path("unsubscribe/<uuid:uuid>/", UnSubscribe.as_view(), name="end_news"),
    path("feedback/", ContactView.as_view(), name="feedback"),
]

src/core/urls.py
from django.urls import path

from .views import about, intro, thanks

app_name = "core"

urlpatterns = [
    path("general-info/", intro, name="intro"),
    path("acknowledgments/", thanks, name="thanks"),
    path("about/", about, name="about"),
]

src/devs/urls.py
from django.urls import path

from .views import (
    ChangeState,
    DevDetailPost,
    DevPage,
    MakeNewPost,
    ShowDevPostList,
    SoftDeletePost,
)

app_name = "devs"

urlpatterns = [
    path("", DevPage.as_view(), name="dev_page"),
    path("drafts/<action>/", ShowDevPostList.as_view(), name="selection"),
    path(
        "dev-post-detail/<str:uuid>/",
        DevDetailPost.as_view(),
        name="dev_detail_post",
    ),
    path("soft-delete/<str:uuid>/", SoftDeletePost.as_view(), name="soft_delete_post"),
    path("change-state/<action>/", ChangeState.as_view(), name="change_state"),
    path("creation/", MakeNewPost.as_view(), name="creation"),
]

src/notifications/urls.py
from django.urls import path

from .views import get_top_five, make_notifs_read

app_name = "notifications"

urlpatterns = [
    path("", get_top_five, name="all_notifics"),
    path("make-as-read/", make_notifs_read, name="mark_top_read"),
]

src/posts/urls.py
from django.urls import path, re_path

from src.posts.views.post_views import (
    PostBookMarkCollection,
    PostCategSearch,
    PostComment,
    PostDatumFilter,
    PostList,
    PostTagSearch,
    SearchPost,
)
from src.posts.views.user_action_views import TrackBookmark, TrackLike

app_name = "posts"

urlpatterns = [
    path("", PostList.as_view(), name="post_list"),
    path("detail/<slug:slug>/", PostComment.as_view(), name="post_detail"),
    path("categ/<slug:slug>/", PostCategSearch.as_view(), name="cat_search"),
    path("search/", SearchPost.as_view(), name="search_posts"),
    re_path(
        r"^tag-search/(?:t:(?P<tag>[-\w]+)/)?$",
        PostTagSearch.as_view(),
        name="tag_search",
    ),
    path(
        "comments/<slug:slug>/<thread_uuid>/", PostComment.as_view(), name="get_branch"
    ),
    path(
        "datum-filter/<year>/<month>/",
        PostDatumFilter.as_view(),
        name="filter_calend",
    ),
    path(
        "change-bookmark/<action>/",
        TrackBookmark.as_view(),
        name="change_bookmark",
    ),
    # part delete bmark => htmx
    path(
        "bmark-collection/", PostBookMarkCollection.as_view(), name="bmark_collection"
    ),
]

htmx_urlpatterns = [
    path("set-like/", TrackLike.as_view(), name="track_likes"),
]
urlpatterns += htmx_urlpatterns

src/profiles/urls.py
from django.urls import path

from .views import ProfileDelete, ProfileView

app_name = "profiles"

urlpatterns = [
    path("<uuid:uuid>/", ProfileView.as_view(), name="profile_detail"),
    path("delete/<uuid:uuid>/", ProfileDelete.as_view(), name="profile_delete"),
]

src/accounts/forms.py
from allauth.account.forms import SignupForm
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm as UCF
from django.utils.html import format_html
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserCreationForm(UCF):
    """form to create a new user via admin (door admin)"""

    email = forms.EmailField(
        label=_("Email"),
        max_length=120,
        widget=forms.EmailInput(attrs={"autocomplete": "email"}),
    )

    class Meta(UCF.Meta):
        model = User
        fields = ("username", "email")


# custom allauth form
class CustomSignupForm(SignupForm):
    """add extra field for 'Agree'"""

    username_help_text = "Username should contain at least 3 characters"
    password_help_text = (
        "Password should contain at least 8 characters; can not be entirely numeric"
    )

    def __init__(self, *args, **kwargs):
        """included field "agree to term" needs other css styling"""
        super().__init__(*args, **kwargs)
        self.fields["username"].help_text = self.username_help_text
        self.fields["password1"].help_text = self.password_help_text

        self.fields["agree_to_terms"].widget.attrs = {"type": "checkbox"}
        for field_name, field in self.fields.items():
            if field_name != "agree_to_terms":
                field.widget.attrs = {"class": "form-control border border-4"}
            else:
                field.widget.attrs = {"class": "mt-2 mb-4"}

    agree_to_terms = forms.BooleanField(
        label=format_html(
            _(
                "I agree to the <a class='general' \
                href='/terms'>terms and conditions</a>"
            )
        )
    )

    field_order = ("username", "email", "password1", "password2", "agree_to_terms")

src/accounts/views.py
from allauth.account.views import SignupView
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404, render

User = get_user_model()


class CustomSignUp(SignupView):
    """if user deleted his account=> show account not active template"""

    def form_valid(self, form):
        user_email = form.cleaned_data["email"]
        user_obj = get_object_or_404(User, email=user_email)
        if user_obj is not None and not user_obj.is_active:
            return render(self.request, template_name="account/account_inactive.html")
        print("inside line 14")
        return super().form_valid(form)

src/comments/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin as LRM
from django.http import HttpResponse, HttpResponseForbidden, QueryDict
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.views import View

from src.comments.forms import CommentForm
from src.comments.mixins import CheckRequestMixin
from src.comments.models import Comment
from src.posts.models.post_model import Post

logger = logging.getLogger("user_issues")


def display_all_comments(request, post_uuid):
    """
    htmx based; triggered if post detail page
    loaded or comments updated
    """
    post = Post.objects.get(uuid=post_uuid)
    post_comms = Comment.objects.filter(post=post)
    return render(
        request,
        "components/comms/wraps.html",
        {"comments": post_comms, "post": post, "user": request.user},
    )


def display_selected_comments(request, post_uuid, thread_uuid):
    """
    htmx based;
    triggered from dropdown-menu link:
    comments refer to replied comment and it's children
    """
    post = Post.objects.get(uuid=post_uuid)
    post_comms = Comment.objects.filter(post=post, uuid=thread_uuid)
    return render(
        request,
        "components/comms/wraps.html",
        {"comments": post_comms, "post": post, "user": request.user},
    )


class GetReplyFormView(LRM, CheckRequestMixin, View):
    def get(self, request, post_uuid, comm_id):
        """htmx + modal; get req to get form for reply"""
        form = CommentForm(initial={"comm_parent_id": comm_id})
        ctx = {}
        ctx["form"] = form
        ctx["post_uuid"] = post_uuid
        return render(request, "components/comms/comm_form.html", ctx)


class ProccessReplyView(LRM, CheckRequestMixin, View):
    def post(self, request, post_uuid):
        """
        htmx-modal;
        no notifications in cases:
        - parent(replied) comm is deleted;
        - users comment their own comment
        - banned users filter via template
        """
        form = CommentForm(request.POST)
        if form.is_valid():
            comm_parent_id = form.cleaned_data["comm_parent_id"]
            post = get_object_or_404(Post, uuid=post_uuid)
            parent_comm = get_object_or_404(Comment, id=comm_parent_id)
            replied_to = parent_comm.user
            comm = form.save(commit=False)
            comm_body = form.cleaned_data["body"]
            comm.user = request.user
            comm.reply_to = replied_to
            comm.post = post
            comm.body = comm_body
            if replied_to == request.user:
                comm.own_reply = True
            parent_comm.add_child(instance=comm)
            return HttpResponse(status=204, headers={"HX-Trigger": "updateCommList"})


@login_required
def handle_edit_comment(request, post_uuid, comm_id):
    """
    htmx based + modal UI in bootstrap5;
    provide pre-filled comment form and proccess it.
    incl method PUT (htmx)
    """
    if request.user.banned:
        logger.warning(f"banned user {request.user.id} attempted to edit comment")
        return HttpResponseForbidden()

    ctx = {"post_uuid": post_uuid, "comm_id": comm_id}
    post = get_object_or_404(Post, uuid=post_uuid)
    obj = get_object_or_404(Comment, post_id=post.id, id=comm_id)
    parent = obj.get_parent()
    if request.method == "GET":
        if parent:
            form = CommentForm(instance=obj, initial={"comm_parent_id": comm_id})
        else:
            form = CommentForm(instance=obj)
        ctx["form"] = form
        return render(request, "components/comms/comm_edit_form.html", ctx)

    if request.method == "PUT":
        data_dict = QueryDict(request.body).dict()
        form = CommentForm(data_dict, instance=obj)
        if form.is_valid():
            obj.updated_at = timezone.now()
            obj.save()
            return HttpResponse(status=204, headers={"HX-Trigger": "updateCommList"})
        else:
            ctx["form"] = form
    return render(request, "components/comms/comm_edit_form.html", ctx)


class DeleteCommentView(LRM, CheckRequestMixin, View):
    def get(self, request, post_uuid, comm_id):
        ctx = {"post_uuid": post_uuid, "comm_id": comm_id}
        return render(request, "components/comms/del_confirm.html", ctx)

    def post(self, request, post_uuid, comm_id):
        post = get_object_or_404(Post, uuid=post_uuid)
        comm_to_del = get_object_or_404(Comment, id=comm_id, post_id=post.id)
        comm_to_del.deleted = True
        comm_to_del.save()
        return HttpResponse(status=204, headers={"HX-Trigger": "updateCommList"})

src/contacts/views.py
import logging

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin as LRM
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import View
from django.views.generic.edit import FormView

from src.core.utils.views_help import get_ip
from src.profiles.models import Profile

from .exceptions import HtmxFailureError
from .forms import ContactForm

logger = logging.getLogger("user_issues")


class Subscribe(LRM, View):
    def get(self, request):
        """
        only auth-ed users can subscribe to a news letter
        via menu dropdown item
        """
        return render(
            request,
            "contacts/subscription/confirmation.html",
        )

    def post(self, request, **kwargs):
        """
        htmx_based request with redirect to home page
        and flash msg as a feedback
        """

        htmx_req = request.headers.get("hx-request")

        if request.user.is_authenticated and htmx_req is not None:
            _id = request.user.profile.id
            profile = get_object_or_404(Profile, id=_id)
            profile.want_news = True
            profile.save()
            logger.info(f"{profile.id} succeeded to subscribe for news letter")
            messages.success(request, _("You have subscribed to the news letter"))
            return HttpResponse(
                headers={"HX-Redirect": "/"},
            )
        elif htmx_req is None:
            logger.error(f"{request.user.id} failed htmx to subscribe for news letter")
            raise HtmxFailureError(_("Subscription failed"))


class UnSubscribe(View):
    def get(self, request, **kwargs):
        """
        get request via link in a newsletter
        contains profile uuid
        """
        uuid = kwargs.get("uuid")
        profile = get_object_or_404(Profile, uuid=uuid)
        ctx = {"uuid": profile.uuid}
        return render(request, "contacts/subscription/unsubscribe.html", ctx)

    def post(self, request, **kwargs):
        # htmx_based
        """
        if OK -> redirect ot Home page with success msg
        """
        htmx_req = request.headers.get("hx-request")
        try:
            uuid = kwargs.get("uuid")
            profile = get_object_or_404(Profile, uuid=uuid)
            if htmx_req and profile.want_news:
                profile.want_news = False
                profile.save()
                logger.info(f"{profile.id} succeeded to UNsubscribe for news letter")
                messages.success(request, _("You have unsubscribed to the news letter"))
                return HttpResponse(
                    headers={
                        "HX-Redirect": "/",
                    },
                )
            elif htmx_req is None:
                logger.error(f"{profile.id} failed htmx to Unsubscribe for news letter")
                raise HtmxFailureError(_("Something went wrong.Can't unsubscribe."))
        except HtmxFailureError:
            raise

        return HttpResponseRedirect("/")


class ContactView(FormView):
    """unauth or auth user can send a feedback to admin"""

    template_name = "contacts/feedback/feedback.html"
    form_class = ContactForm
    success_url = reverse_lazy("home")

    def get_form_kwargs(self) -> dict:
        kwargs = super().get_form_kwargs()
        if self.request.user.is_authenticated:
            kwargs.update(
                {
                    "initial": {
                        "name": self.request.user.username,
                        "email": self.request.user.email,
                    }
                }
            )
        return kwargs

    def form_valid(self, form):
        name = form.cleaned_data.get("name")
        email = form.cleaned_data.get("email")
        subject = form.cleaned_data.get("subject")
        message = form.cleaned_data.get("message")
        context = {
            "user": name,
            "subject": subject,
            "email": email,
            "message": message,
        }

        from_email = email
        to_email = ("some-mail@mail.com",)
        contact_message = get_template("contacts/feedback/contact_msg.txt").render(
            context
        )

        # self.send_mail_to_admin() ?
        send_mail(subject, contact_message, from_email, to_email, fail_silently=True)
        remote_address = get_ip(self.request)
        logger.info(f"contact letter sent OK from ip: {remote_address}")

        messages.add_message(
            self.request,
            messages.SUCCESS,
            _("Your message is sent"),
        )

        return HttpResponseRedirect(redirect_to=self.success_url)

src/core/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

from src.posts.models.media_model import Video


def home(request: HttpRequest) -> HttpResponse:
    # ctx = {"vidos": Video.objects.last()}
    return render(request, "core/home.html")  # , ctx)


def intro(request: HttpRequest) -> HttpResponse:
    ctx = {}
    return render(request, "core/intro.html", ctx)


def about(request: HttpRequest) -> HttpResponse:
    ctx = {}
    return render(request, "core/about.html", ctx)


def thanks(request: HttpRequest) -> HttpResponse:
    ctx = {}
    return render(request, "core/acknowledgments.html", ctx)

src/templates/components/categ_bar.html
{% load sidebars %}

<div class="drop-top" >
    <button class="btn btn-secondary hide" id="show-cats" data-dropdown-but>Show Categories</button>
    <ul class="root-cats mt-3" data-dropdown>
    {% recursetree categs %}
        <li class="node-name categ_item" data-li>
          {% if node.is_leaf %}
          <a hx-get="{% url 'posts:cat_search' node.slug %}" hx-target="#post_list" class="node-link" >{{node.name}} {{node.num}}</a>
          {% else %}
          <!-- 2 siblings: a tag and ul children -->
            <a hx-get="{% url 'posts:cat_search' node.slug %}" hx-target="#post_list" class="node-link to-toggle" data-dropdown-link>{{node.name}} &#x25B8; {{node.num}}</a>
            <ul class="children">
              {{ children }}
            </ul>
          {% endif %}
        </li>
        {% endrecursetree %}
    </ul>
</div>

src/templates/components/crumbs.html
{% load static i18n%}

<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);"aria-label="breadcrumb">
  <ol class="breadcrumb">
    {% for item in crumbs  %}
    {% if forloop.first %}
    <li class="breadcrumb-item">
      <a href="{{item.url}}" class="">
        <!-- <img src="{% static 'images/svgs/home.svg' %}" alt="avatar" style="width:42px;height:42px;" > -->
        <span>{% trans 'Home' %}</span>
    </a>
  </li>
  {% else %}
    <li class="breadcrumb-item">
      <a href="{{item.url}}" class="d-flex ml-1">
        {{item.name}}
    </a>
  </li>
  {% endif %}
  {% endfor %}

</ol>
</nav>

src/templates/components/htmx_pags.html
<!-- start pagination       -->
  <div class="pagination mt-3 p-3">
    <ul class="pag-wrapper">
        <li><a hx-get="{{req_url}}?page=1" hx-target="#post_list">
                    <i class="fas fa-angle-double-left"></i>
                </a>
         </li>
        {% if page_obj.has_previous%}
        <li>
            <a hx-get="{{req_url}}?page={{page_obj.previous_page_number}}" hx-target="#post_list">
                <i class="fa fa-long-arrow-left"></i>
            </a>
        </li>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if num == page_obj.number %}
                <li><a href="#" class="active">{{num}}</a></li>

            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
                <li><a hx-get="{{req_url}}?page={{num}}" hx-target="#post_list">{{num}}</a></li>
            {% endif %}

        {% endfor %}
        {% if page_obj.has_next%}
        <li><a hx-get="{{req_url}}?page={{page_obj.next_page_number}}" hx-target="#post_list">
            <i class="fa fa-long-arrow-right"></i>
        </a>
        </li>
        {% endif %}
        <li><a hx-get="{{req_url}}?page={{page_obj.paginator.num_pages}}" hx-target="#post_list"><i class="fas fa-angle-double-right"></i>
        </a>
    </li>
  </ul>
</div>
<!-- end pagination -->

src/templates/components/menu.html
{% load widget_tweaks static i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}


<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top navbar-custom p-3">
    <div class="container-fluid align-items-md-baseline">
      <a class="navbar-brand logo" href="/">MedSandBox</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse fs-4" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <!-- <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li> -->
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'posts:post_list'%}">{% trans 'Posts'%}</a>
          </li>


          <li class="nav-item">
            <a class="nav-link" href="{% url 'contacts:feedback' %}">{% trans 'Contact' %}
            </a>
          </li>
          {% if user.is_authenticated %}
            {% if user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'devs:dev_page' %}">
                {% trans 'Dashboard' %}
              </a>
            </li>
            {% endif %}

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{user.username}}
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" id="subLink" href="{% url 'profiles:profile_detail' uuid=user.profile.uuid %}">{% trans "Profile" %}</a>
              </li>
              {% if has_bookmarks %}
              <li><hr class="dropdown-divider"></li>
              <li >
                <a class="dropdown-item" href="{% url 'posts:bmark_collection' %}">
                  {% trans 'Bookmarks' %} <svg viewBox="0 0 16 16" width="1em" height="1em" focusable="false" role="img" aria-label="bookmark heart fill" xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi-bookmark-heart-fill b-icon bi"><g><path d="M2 15.5a.5.5 0 0 0 .74.439L8 13.069l5.26 2.87A.5.5 0 0 0 14 15.5V2a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v13.5zM8 4.41c1.387-1.425 4.854 1.07 0 4.277C3.146 5.48 6.613 2.986 8 4.412z"></path></g></svg>
              </a>

              </li>
              {% endif %}

              {% if not news_negative %}
              <li><hr class="dropdown-divider"></li>
              <li class="nav-item">
              <a class="dropdown-item" href="{% url 'contacts:subscribe' %}" >
                  {% trans 'Subscribe to news' %}
              </a>
            </li>
            {% else %}
            <li><hr class="dropdown-divider"></li>
              <li class="nav-item">
              <a class="dropdown-item" href="{% url 'contacts:end_news' user.profile.uuid %}" >
                  {% trans 'Usubscribe to news' %}
              </a>
            </li>
            {% endif %}
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_logout' %}">
                {% trans 'Log out' %}
            </a>
          </li>

          <li class="nav-item">
            <a href="#" class="nav-link bell">
              <img src="{% static 'images/bell48.png' %}" alt="notifications">
            </a>
          </li>
        {% if notifs %}
          <li class="nav-item dropdown">
            <div class="note-badge">
            <a class="nav-link dropdown-toggle" role="button"
            data-bs-toggle="dropdown" aria-expanded="false"
            id="notifs"
            hx-get="{% url 'notifications:all_notifics' %}"
            hx-target="#notis">
               <span class="badge rounded-pill bg-danger">{{notifs}}</span>
              </a>
              <div class="dropdown-menu" aria-labelledby="notifs" id="notis">
              </div>
            </div>
          </li>
          {% endif %}
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_signup' %}">{% trans 'Sign Up' %}
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_login' %}">
                {% trans 'Log In' %}
              </a>
            </li>
        {% endif %}
      </ul>

      <form action="{% url 'set_language' %}" method="post">
        {% csrf_token %}
        <input name="next" type="hidden" value="{{ redirect_to }}">
        <select name="language" class="lang-drop">
            {% for language in languages %}
                <option class="lang-drop__item" value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                    {{ language.code }}

                </option>
            {% endfor %}
        </select>
        <input type="submit" class="but-go" value="Go">
      </form>

    </div>
  </div>
  </nav>
</header>
{% block js %}

{% endblock js%}

src/templates/components/post_categs.html
{% load static %}
<!-- categ path for post detail  -->
<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);"aria-label="breadcrumb">
  <ol class="breadcrumb" id="post_categ">
    {% for item in categ_dict  %}
    <li class="breadcrumb-item">
      <a href="{{item.path}}" class="post_categ__link">
        {{item.name}}
    </a>
    </li>
  {% endfor %}
  </ol>
</nav>

src/templates/components/search.html
<div class="search-inner pe-sm-0 mt-5 mt-md-1">
    <form method="get" class="search-form" id="search" action="{% url 'posts:search_posts' %}">
      <div class="search-box pe-sm-0">
            {{search_form}}
            <a href="#" class="search-btn">
                <button class="custom-invisible" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </a>
      </div>
    </form>
</div>

src/templates/components/splash.html
<div id="hero-img"  class="py-1 py-md-5 text-white">
  <div class="">
    <div class="row">
      <div class="">
      </div>
    </div>

  </div>
  </div>

src/templates/components/tags.html
<div class="mt-3 pt-2">
  <h5 class="text-center fw-bold">Tags</h3>
    <div class="d-flex flex-wrap justify-content-center pt-2 pb-2">
      {% if tags %}
      {% for tag in tags %}
      <div class="m-1 tag_item">
          <a hx-get="{% url 'posts:tag_search' tag=tag.slug %}"
          hx-target="#post_list" class="tag-link">
          <span class="badge bg-outline fs-6"><span class="circle_num">{{tag.count}} </span> &nbsp; {{ tag }}
          </span>
        </a>
      </div>
      {% endfor %}
      {% else %}
      <h4>No tags yet</h4>
      {% endif%}
   </div>
</div>