sandbox/urls.py
"""config URL Configuration 4.1"""

from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from src.accounts.views import CustomSignUp
from src.core.utils.views_help import clear, terms
from src.core.views import home

# handler404 = "src.core.utils.views_help.handler404"
# handler500 = "src.core.utils.views_help.handler500"


urlpatterns = [
    # path(eve('SECRET_ADMIN_URL') + '/admin/', admin.site.urls),
    path(
        "i18n/",
        include("django.conf.urls.i18n"),
    ),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path("admin/", admin.site.urls),
    path("contacts/", include("src.contacts.urls")),
    path("notifications/", include("src.notifications.urls")),
    path("in-development/", include("src.devs.urls")),
    path("terms", terms, name="terms"),
]

htmx_urlpatterns = [
    path("clear", clear, name="clear"),
]

urlpatterns += i18n_patterns(
    path("", home, name="home"),
    path("accounts/signup/", CustomSignUp.as_view()),
    path("accounts/", include("allauth.urls")),
    path("core/", include("src.core.urls")),
    path("profile/", include("src.profiles.urls")),
    path("posts/", include("src.posts.urls")),
    path("comments/", include("src.comments.urls")),
)
urlpatterns += htmx_urlpatterns
if "rosetta" in settings.INSTALLED_APPS:
    urlpatterns += [path("rosetta/", include("rosetta.urls"))]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

src/core/urls.py
from django.urls import path

from .views import about, intro, thanks

app_name = "core"

urlpatterns = [
    path("general-info/", intro, name="intro"),
    path("acknowledgments/", thanks, name="thanks"),
    path("about/", about, name="about"),
]

src/devs/urls.py
from django.urls import path

from .views import (
    ChangeState,
    DevDetailPost,
    DevPage,
    MakeNewPost,
    ShowDevPostList,
    SoftDeletePost,
)

app_name = "devs"

urlpatterns = [
    path("", DevPage.as_view(), name="dev_page"),
    path("drafts/<action>/", ShowDevPostList.as_view(), name="selection"),
    path(
        "dev-post-detail/<str:uuid>/",
        DevDetailPost.as_view(),
        name="dev_detail_post",
    ),
    path("soft-delete/<str:uuid>/", SoftDeletePost.as_view(), name="soft_delete_post"),
    path("change-state/<action>/", ChangeState.as_view(), name="change_state"),
    path("creation/", MakeNewPost.as_view(), name="creation"),
]

src/posts/urls.py
from django.urls import path, re_path

from src.posts.views.post_views import (
    PostBookMarkCollection,
    PostCategSearch,
    PostComment,
    PostDatumFilter,
    PostList,
    PostTagSearch,
    SearchPost,
)
from src.posts.views.user_action_views import TrackBookmark, TrackLike

app_name = "posts"

urlpatterns = [
    path("", PostList.as_view(), name="post_list"),
    path("detail/<slug:slug>/", PostComment.as_view(), name="post_detail"),
    path("categ/<slug:slug>/", PostCategSearch.as_view(), name="cat_search"),
    path("search/", SearchPost.as_view(), name="search_posts"),
    re_path(
        r"^tag-search/(?:t:(?P<tag>[-\w]+)/)?$",
        PostTagSearch.as_view(),
        name="tag_search",
    ),
    path(
        "comments/<slug:slug>/<thread_uuid>/", PostComment.as_view(), name="get_branch"
    ),
    path(
        "datum-filter/<year>/<month>/",
        PostDatumFilter.as_view(),
        name="filter_calend",
    ),
    path(
        "change-bookmark/<action>/",
        TrackBookmark.as_view(),
        name="change_bookmark",
    ),
    # part delete bmark => htmx
    path(
        "bmark-collection/", PostBookMarkCollection.as_view(), name="bmark_collection"
    ),
]

htmx_urlpatterns = [
    path("set-like/", TrackLike.as_view(), name="track_likes"),
]
urlpatterns += htmx_urlpatterns

src/posts/models/post_model.py
import uuid

from autoslug import AutoSlugField
from django.contrib.auth import get_user_model
from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVectorField
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from taggit.managers import TaggableManager
from unidecode import unidecode  # noqa

from src.core.models import TimeStamp
from src.core.utils.base import upload_img
from src.posts.managers import PostFilterManager
from src.posts.models.categ_model import Category

User = get_user_model()


class Post(TimeStamp):
    """pivotal model;"""

    class CurrentStatus(models.IntegerChoices):
        DRAFT = 0, _("drafts")
        REVIEW = 1, _("reviews")
        PUB = 2, _("published")

    class SendingStatus(models.IntegerChoices):
        PENDING = 0, _("pend")
        READY = 1, _("to send")
        SENT = 2, _("sent")

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=255)
    slug = AutoSlugField(populate_from="title", unique=True, editable=True, blank=True)
    categ = models.ForeignKey(
        Category,
        on_delete=models.SET_DEFAULT,
        default=Category.get_default_pk,
        related_name="posts",
    )
    content = models.TextField()
    top_img = models.ImageField(upload_to=upload_img, null=True, blank=True)
    url_top_img = models.URLField(blank=True, default="")
    status = models.IntegerField(
        choices=CurrentStatus.choices, default=CurrentStatus.DRAFT, blank=True
    )
    is_deleted = models.BooleanField(default=False)
    published_at = models.DateTimeField(null=True, blank=True)
    featured = models.BooleanField(blank=True, default=False)
    allow_comments = models.BooleanField(default=True)
    send_status = models.IntegerField(
        choices=SendingStatus.choices, default=SendingStatus.PENDING, blank=True
    )
    letter = models.ForeignKey(
        "contacts.NewsLetter",
        related_name="posts",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    tags = TaggableManager(
        blank=True, verbose_name="Tags", help_text="Tags should be separated by comma"
    )
    fans = models.ManyToManyField(User, related_name="post_fans", through="Relation")
    count_likes = models.IntegerField(default=None, null=True, blank=True)
    count_bmarks = models.IntegerField(default=None, null=True, blank=True)
    vector_ru = SearchVectorField(null=True, blank=True)
    vector_en = SearchVectorField(null=True, blank=True)

    objects = PostFilterManager.as_manager()

    class Meta:
        ordering = ["-created_at"]
        indexes = (GinIndex(fields=["vector_ru", "vector_en"]),)

    def soft_delete(self):
        """soft  delete a model instance"""
        self.is_deleted = True
        self.save()

    def get_absolute_url(self):
        return reverse("posts:detail_post", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        """auto create datetime if public status changes"""
        if self.status == 2:
            self.published_at = timezone.now()  # .date() no time part
        else:
            self.published_at = None
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return f"{self.title} | {self.author}"

src/accounts/views.py
from allauth.account.views import SignupView
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404, render

User = get_user_model()


class CustomSignUp(SignupView):
    """if user deleted his account=> show account not active template"""

    def form_valid(self, form):
        user_email = form.cleaned_data["email"]
        user_obj = get_object_or_404(User, email=user_email)
        if user_obj is not None and not user_obj.is_active:
            return render(self.request, template_name="account/account_inactive.html")
        print("inside line 14")
        return super().form_valid(form)

src/comments/views.py
import logging

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin as LRM
from django.http import HttpResponse, HttpResponseForbidden, QueryDict
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.views import View

from src.comments.forms import CommentForm
from src.comments.mixins import CheckRequestMixin
from src.comments.models import Comment
from src.posts.models.post_model import Post

logger = logging.getLogger("user_issues")


def display_all_comments(request, post_uuid):
    """
    htmx based; triggered if post detail page
    loaded or comments updated
    """
    post = Post.objects.get(uuid=post_uuid)
    post_comms = Comment.objects.filter(post=post)
    return render(
        request,
        "components/comms/wraps.html",
        {"comments": post_comms, "post": post, "user": request.user},
    )


def display_selected_comments(request, post_uuid, thread_uuid):
    """
    htmx based;
    triggered from dropdown-menu link:
    comments refer to replied comment and it's children
    """
    post = Post.objects.get(uuid=post_uuid)
    post_comms = Comment.objects.filter(post=post, uuid=thread_uuid)
    return render(
        request,
        "components/comms/wraps.html",
        {"comments": post_comms, "post": post, "user": request.user},
    )


class GetReplyFormView(LRM, CheckRequestMixin, View):
    def get(self, request, post_uuid, comm_id):
        """htmx + modal; get req to get form for reply"""
        form = CommentForm(initial={"comm_parent_id": comm_id})
        ctx = {}
        ctx["form"] = form
        ctx["post_uuid"] = post_uuid
        return render(request, "components/comms/comm_form.html", ctx)


class ProccessReplyView(LRM, CheckRequestMixin, View):
    def post(self, request, post_uuid):
        """
        htmx-modal;
        no notifications in cases:
        - parent(replied) comm is deleted;
        - users comment their own comment
        - banned users filter via template
        """
        form = CommentForm(request.POST)
        if form.is_valid():
            comm_parent_id = form.cleaned_data["comm_parent_id"]
            post = get_object_or_404(Post, uuid=post_uuid)
            parent_comm = get_object_or_404(Comment, id=comm_parent_id)
            replied_to = parent_comm.user
            comm = form.save(commit=False)
            comm_body = form.cleaned_data["body"]
            comm.user = request.user
            comm.reply_to = replied_to
            comm.post = post
            comm.body = comm_body
            if replied_to == request.user:
                comm.own_reply = True
            parent_comm.add_child(instance=comm)
            return HttpResponse(status=204, headers={"HX-Trigger": "updateCommList"})


@login_required
def handle_edit_comment(request, post_uuid, comm_id):
    """
    htmx based + modal UI in bootstrap5;
    provide pre-filled comment form and proccess it.
    incl method PUT (htmx)
    """
    if request.user.banned:
        logger.warning(f"banned user {request.user.id} attempted to edit comment")
        return HttpResponseForbidden()

    ctx = {"post_uuid": post_uuid, "comm_id": comm_id}
    post = get_object_or_404(Post, uuid=post_uuid)
    obj = get_object_or_404(Comment, post_id=post.id, id=comm_id)
    parent = obj.get_parent()
    if request.method == "GET":
        if parent:
            form = CommentForm(instance=obj, initial={"comm_parent_id": comm_id})
        else:
            form = CommentForm(instance=obj)
        ctx["form"] = form
        return render(request, "components/comms/comm_edit_form.html", ctx)

    if request.method == "PUT":
        data_dict = QueryDict(request.body).dict()
        form = CommentForm(data_dict, instance=obj)
        if form.is_valid():
            obj.updated_at = timezone.now()
            obj.save()
            return HttpResponse(status=204, headers={"HX-Trigger": "updateCommList"})
        else:
            ctx["form"] = form
    return render(request, "components/comms/comm_edit_form.html", ctx)


class DeleteCommentView(LRM, CheckRequestMixin, View):
    def get(self, request, post_uuid, comm_id):
        ctx = {"post_uuid": post_uuid, "comm_id": comm_id}
        return render(request, "components/comms/del_confirm.html", ctx)

    def post(self, request, post_uuid, comm_id):
        post = get_object_or_404(Post, uuid=post_uuid)
        comm_to_del = get_object_or_404(Comment, id=comm_id, post_id=post.id)
        comm_to_del.deleted = True
        comm_to_del.save()
        return HttpResponse(status=204, headers={"HX-Trigger": "updateCommList"})

src/contacts/views.py
import logging

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin as LRM
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import View
from django.views.generic.edit import FormView

from src.core.utils.views_help import get_ip
from src.profiles.models import Profile

from .exceptions import HtmxFailureError
from .forms import ContactForm

logger = logging.getLogger("user_issues")


class Subscribe(LRM, View):
    def get(self, request):
        """
        only auth-ed users can subscribe to a news letter
        via menu dropdown item
        """
        return render(
            request,
            "contacts/subscription/confirmation.html",
        )

    def post(self, request, **kwargs):
        """
        htmx_based request with redirect to home page
        and flash msg as a feedback
        """

        htmx_req = request.headers.get("hx-request")

        if request.user.is_authenticated and htmx_req is not None:
            _id = request.user.profile.id
            profile = get_object_or_404(Profile, id=_id)
            profile.want_news = True
            profile.save()
            logger.info(f"{profile.id} succeeded to subscribe for news letter")
            messages.success(request, _("You have subscribed to the news letter"))
            return HttpResponse(
                headers={"HX-Redirect": "/"},
            )
        elif htmx_req is None:
            logger.error(f"{request.user.id} failed htmx to subscribe for news letter")
            raise HtmxFailureError(_("Subscription failed"))


class UnSubscribe(View):
    def get(self, request, **kwargs):
        """
        get request via link in a newsletter
        contains profile uuid
        """
        uuid = kwargs.get("uuid")
        profile = get_object_or_404(Profile, uuid=uuid)
        ctx = {"uuid": profile.uuid}
        return render(request, "contacts/subscription/unsubscribe.html", ctx)

    def post(self, request, **kwargs):
        # htmx_based
        """
        if OK -> redirect ot Home page with success msg
        """
        htmx_req = request.headers.get("hx-request")
        try:
            uuid = kwargs.get("uuid")
            profile = get_object_or_404(Profile, uuid=uuid)
            if htmx_req and profile.want_news:
                profile.want_news = False
                profile.save()
                logger.info(f"{profile.id} succeeded to UNsubscribe for news letter")
                messages.success(request, _("You have unsubscribed to the news letter"))
                return HttpResponse(
                    headers={
                        "HX-Redirect": "/",
                    },
                )
            elif htmx_req is None:
                logger.error(f"{profile.id} failed htmx to Unsubscribe for news letter")
                raise HtmxFailureError(_("Something went wrong.Can't unsubscribe."))
        except HtmxFailureError:
            raise

        return HttpResponseRedirect("/")


class ContactView(FormView):
    """unauth or auth user can send a feedback to admin"""

    template_name = "contacts/feedback/feedback.html"
    form_class = ContactForm
    success_url = reverse_lazy("home")

    def get_form_kwargs(self) -> dict:
        kwargs = super().get_form_kwargs()
        if self.request.user.is_authenticated:
            kwargs.update(
                {
                    "initial": {
                        "name": self.request.user.username,
                        "email": self.request.user.email,
                    }
                }
            )
        return kwargs

    def form_valid(self, form):
        name = form.cleaned_data.get("name")
        email = form.cleaned_data.get("email")
        subject = form.cleaned_data.get("subject")
        message = form.cleaned_data.get("message")
        context = {
            "user": name,
            "subject": subject,
            "email": email,
            "message": message,
        }

        from_email = email
        to_email = ("some-mail@mail.com",)
        contact_message = get_template("contacts/feedback/contact_msg.txt").render(
            context
        )

        # self.send_mail_to_admin() ?
        send_mail(subject, contact_message, from_email, to_email, fail_silently=True)
        remote_address = get_ip(self.request)
        logger.info(f"contact letter sent OK from ip: {remote_address}")

        messages.add_message(
            self.request,
            messages.SUCCESS,
            _("Your message is sent"),
        )

        return HttpResponseRedirect(redirect_to=self.success_url)

src/templates/posts/parts/archive.html
{% load i18n %}
<div class="mb-2  pb-2">
  <h4>{%trans 'History' %}</h4>
  {% for year,month_info in archives %}
  <div class="dropdown">
      <button class="btn btn-secondary btn-lg dropdown-toggle archive" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        {{year}}
      </button>
      <ul class="dropdown-menu">
        {% for items in month_info %}
          <li><a class="dropdown-item" hx-get="{% url 'posts:filter_calend' year=year month=items.0 %}" hx-target="#post_list" class="calend_item">{{items.0|date:"F"}}-<span class="circle_num">{{items.1}}</span></a></li>
        {% endfor %}
      </ul>
    </div>
  {% endfor %}

</div>

src/templates/posts/parts/pagination.html
<div class="pagination mt-2">
    <ul class="pag-wrapper">
        <li><a href="?page=1">
                <i class="fas fa-angle-double-left"></i>
            </a>
        </li>
        {% if page_obj.has_previous%}
            <li>
                <a href="?page={{page_obj.previous_page_number}}">
                    <i class="fa fa-long-arrow-left"></i>
                </a>
            </li>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if num == page_obj.number %}
                <li><a href="#" class="active">{{num}}</a></li>

            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
                <li><a href="?page={{num}}">{{num}}</a></li>
            {% endif %}

        {% endfor %}
        {% if page_obj.has_next%}
        <li><a href="?page={{page_obj.next_page_number}}">
            <i class="fa fa-long-arrow-right"></i>
        </a>
        </li>
        {% endif %}

        <li><a href="?page={{page_obj.paginator.num_pages}}"><i class="fas fa-angle-double-right"></i>
            </a>
        </li>
    </ul>
  </div><!--end pagination-->

src/templates/posts/parts/post_card.html
{% load static i18n %}
<!-- short represention -->
<div class="card m-2" style="width: 28rem;">
  {% if post.top_img %}
  <img src="{{post.top_img.url}}" class="card-img-top" alt="top-img">
  {% endif %}
  <ul class="list-group list-group-flush">
      <li class="list-group-item"><h3>{{post.title}}</h3></li>
      <li class="list-group-item">Published updated {{post.updated_at|date:"F d, Y"}}</li>
      <li class="list-group-item">status = {{post.get_status_display}}</li>
      <li class="list-group-item"><strong>{% trans "category" %}: {{post.categ.name}}</strong></li>
    </ul>
  <div class="card-body">
    <a href="{% url 'devs:dev_detail_post' post.uuid %}"><button class="btn btn-primary">More details</button></a>
  </div>
  <div><button class="btn btn-danger" id="data-{{post.uuid}}"
    hx-post="{% url 'posts:change_bookmark' action='delete'%}"
    hx-vals='{
      "post_uuid":"{{post.uuid}}",
      "user_id":"{{user.id}}"
    }'
    >Remove from bookmarks</button></div>
</div>

src/templates/posts/parts/posts_collection.html
{% load i18n pags %}
<!-- condition only for tag-,catges search  -->
  {% if posts %}
      {% for post in posts%}
          {% include "posts/parts/single_post.html" %}
      {% endfor %}
      {% pags_htmx tag=tag slug=slug page_obj=page_obj request=request year=year month=month %}
      {% else %}
      <div class= "not-found p-2 fs-3 fs-sm-1 ms-2 me-2" >
        {% trans "Sorry. Nothing found for your search" %}
    </div>

{% endif %}

src/templates/posts/parts/search_errors.html
<div>
    {% if invalid_input %}
    <div class="invalid-input errorlist text-center">{{invalid_input}}</div>
    {% endif %}
    {% if empty_flag %}
    <div class="empty-query errorlist text-center">{{empty_flag}}</div>
    {% endif %}

</div>

src/templates/posts/parts/single_post.html
{% load static i18n %}
<!-- short represention -->
<div class="single_post">
    <div class="single_post__title">{{post.title}}</div>
    {% if post.top_img %}
    <div class="single_post__image d-flex">
      <img src="{{post.top_img.url}}" class="img-fluid" alt="post_img">
    </div>
    {% endif %}
    <div>
      <p class="single_post__date">{{post.published_at|date:"F d, Y"}}</p>
      <p class="single_post__categ">
        <strong>{% trans "category" %}</strong>: {{post.categ.name}}

      </p>
    </div>
    <!-- <div class="single_post_content">
          post.content|truncatewords_html:7|safe}}
    </div> -->
      <div class="single_post__link d-flex">
        <a href="{% url 'posts:post_detail' post.slug %}">
          {% trans 'Read more' %}
        </a>
    </div>
</div>
<hr>

src/templates/posts/parts/tags.html
<h5 class="text-center">Tags</h3>

  <div class="d-flex flex-wrap justify-content-center">
    {% if tags %}
    {% for tag in tags %}
        <div class="m-1"><a href="{% url 'posts:tag_search' tag=tag.slug %}" class="tag-link"><span class="badge bg-dark fs-6">{{ tag }}</span></a></div>
    {% endfor %}
    {% else %}
    <h4>No tags yet</h4>
    {% endif%}
 </div>